### ISSUE TITLE
Bug/On different height of the ContentGroup elements

### ISSUE THREAD

**Issue by jan-capiak** [yusinto/react-site-nav#4] opened 2018-09-06 16:27 UTC
Hello,
I really like this Navbar, but i found a bug, that makes me crazy :)

This Bug can be found as well on your example website here: https://build-licattzisr.now.sh/

When you have like in the example above, different height of ContentGroup, you can see this bug.
![spa-github-menu](https://user-images.githubusercontent.com/39954604/45171237-237eee80-b202-11e8-9524-e7932b01cbbc.png)
![spa-developers-menu](https://user-images.githubusercontent.com/39954604/45171246-2679df00-b202-11e8-97d9-9e29eca2d19d.png)

When you hover over the smaller one, and go below the last <li> item there, the ContentGroup will not hide, but you can actually click on invisible <li> item that belongs to the second ContentGroup, which should be not active.
![spa-github-menu-li-tools](https://user-images.githubusercontent.com/39954604/45171115-da2e9f00-b201-11e8-90eb-e6ada5cd512c.png)

Maybe making inactive ContentGroup hidden would solve this problem, but let me know if you could fix it, because it would be a pitty to leave it with it :)

Thank you man!

**Comment by yusinto** [comment] 2018-09-06 22:06
Hey @jan-capiak I can reproduce the issue. I will take a look soon when I have time. Thanks for reporting!

**Comment by yusinto** [comment] 2018-09-12 08:26
@jan-capiak I've discovered this is a bug related to css-grids. The root component of react-site-nav is a css grid and if a content group contains another css grid, this problem occurs. If the content groups are all using flex, then this bug goes away!

I'll need more time to fix this, but in the interim, perhaps use flex in your content group as a workaround. I'll keep you up to date.

**Comment by yusinto** [comment] 2018-09-13 05:46
@jan-capiak this has been fixed in the latest release [v0.2.7](https://github.com/yusinto/react-site-nav/releases/tag/v0.2.7)

It turns out the overlapping content groups were the problem, not related to css-grid (that was a redherring). Please let me know if it works now! Thanks.

**Comment by jan-capiak** [comment] 2018-09-13 14:07
Hello @yusinto , its working now, great job, I guess we can close this issue now :) thank you

**Comment by yusinto** [comment] 2018-09-14 01:49
@jan-capiak cool! Closing this now.

**Closed by yusinto** 2018-09-14 01:49 UTC
